const autotile = require('autotile')

const collisionData = require('./src/collision.json')

const MAP_WIDTH = 20
const MAP_HEIGHT = 15

const BASE_TILE = 16

const tiles = autotile(
  collisionData.map(
    row => row.map(value => [1, 0][value])
  )
).reduce((tiles, row) => [...tiles, ...row], [])

process.stdout.write('// Autogenerated; do NOT edit!\n')
process.stdout.write('\n')
process.stdout.write('const ground = [\n')

for (let y = 0; y < MAP_HEIGHT; ++y) {
  process.stdout.write('  ')
  for (let x = 0; x < MAP_WIDTH; ++x) {
    process.stdout.write(BASE_TILE + tiles[y * MAP_WIDTH + x] + '')

    if (!(x === MAP_WIDTH - 1 && y === MAP_HEIGHT - 1)) {
      process.stdout.write(',')
    }

    if (x < MAP_WIDTH - 1) {
      process.stdout.write(' ')
    }
  }
  process.stdout.write('\n')
}

process.stdout.write(']\n')
process.stdout.write('\n')
process.stdout.write('export {\n')
process.stdout.write('  ground\n')
process.stdout.write('}\n')
