const SCREEN_WIDTH = 640
const SCREEN_HEIGHT = 480

const TILE_WIDTH = 32
const TILE_HEIGHT = 32

const MAP_WIDTH = SCREEN_WIDTH / TILE_WIDTH
const MAP_HEIGHT = SCREEN_HEIGHT / TILE_HEIGHT

const TILE_SHEET_WIDTH = 8
const TILE_SHEET_HEIGHT = 8

export {
  MAP_HEIGHT,
  MAP_WIDTH,
  SCREEN_HEIGHT,
  SCREEN_WIDTH,
  TILE_HEIGHT,
  TILE_SHEET_HEIGHT,
  TILE_SHEET_WIDTH,
  TILE_WIDTH
}
